output_classes: 9
idm_fps: 4

# Data
idm_batch_size: 2
idm_image_size: [128, 128]
idm_dataset_dir: .cache/pokeagent/rnd_policy_v2
idm_validation_dir: .cache/pokeagent/val
s3_bucket: b4schnei

# Training
idm_epochs: 1
idm_lr: 5.0e-5
idm_weight_decay: 0
idm_max_grad_norm: 1.0
wandb_project: pokeagent
idm_gradient_accumulation_steps: 1
idm_eval_every: 100
idm_scheduler: null
idm_dataloaders_per_device: 16

# Output
idm_output_path: rnd_idm_model.pt
idm_save_every: 1000
